### ISSUE TITLE
Remove the 503 errors

### ISSUE THREAD

**Issue by bamthomas** [ICIJ/datashare-client#14]
When running tests, a bunchs of errors like this happens : 

          [search_phase_execution_exception] all shards failed :: {"path":"/datashare-testjs/doc/_search","query":{},"body":"{\"size\":0,\"query\":{\"bool\":{\"must\":[{\"bool\":{\"should\":[{\"range\":{\"extractionDate\":{\"gte\":\"2018-07-01T00:00:00.000Z\",\"lte\":\"2018-07-31T23:59:59.999Z\"}}}]}},{\"match_all\":{}},{\"bool\":{\"should\":[{\"query_string\":{\"query\":\"*\",\"default_field\":\"*\"}},{\"has_parent\":{\"parent_type\":\"Document\",\"inner_hits\":{\"size\":30},\"query\":{\"match\":{\"content\":\"*\"}}}}]}}]}},\"aggs\":{\"extractionDate\":{\"date_histogram\":{\"field\":\"extractionDate\",\"interval\":\"1M\",\"format\":\"yyyy-MM\"}}}}","statusCode":503,"response":"{\"error\":{\"root_cause\":[],\"type\":\"search_phase_execution_exception\",\"reason\":\"all shards failed\",\"phase\":\"query\",\"grouped\":true,\"failed_shards\":[]},\"status\":503}"}
          at respond (/home/dev/src/datashare-client/node_modules/elasticsearch-browser/elasticsearch.js:25294:15)
          at checkRespForFailure (/home/dev/src/datashare-client/node_modules/elasticsearch-browser/elasticsearch.js:25255:7)
          at XMLHttpRequest.xhr.onreadystatechange (/home/dev/src/datashare-client/node_modules/elasticsearch-browser/elasticsearch.js:31549:7)
          at XMLHttpRequest.el.addEventListener.event (/home/dev/src/datashare-client/node_modules/jsdom/lib/jsdom/living/helpers/create-event-accessor.js:33:32)
          at invokeEventListeners (/home/dev/src/datashare-client/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:193:27)
          at XMLHttpRequestEventTargetImpl._dispatch (/home/dev/src/datashare-client/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:119:9)
          at XMLHttpRequestEventTargetImpl.dispatchEvent (/home/dev/src/datashare-client/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:82:17)
          at XMLHttpRequest.dispatchEvent (/home/dev/src/datashare-client/node_modules/jsdom/lib/jsdom/living/generated/EventTarget.js:157:21)
          at readyStateChange (/home/dev/src/datashare-client/node_modules/jsdom/lib/jsdom/living/xmlhttprequest.js:811:9)
          at Request.properties.client.on (/home/dev/src/datashare-client/node_modules/jsdom/lib/jsdom/living/xmlhttprequest.js:939:7)
          at emitOne (events.js:121:20)
          at Request.emit (events.js:211:7)
          at Gunzip.<anonymous> (/home/dev/src/datashare-client/node_modules/request/request.js:1079:12)
          at Object.onceWrapper (events.js:313:30)
          at emitNone (events.js:111:20)
          at Gunzip.emit (events.js:208:7)
          at endReadableNT (_stream_readable.js:1055:12)
          at _combinedTickCallback (internal/process/next_tick.js:138:11)
          at process._tickCallback (internal/process/next_tick.js:180:9)
    console.error node_modules/jest-jasmine2/build/jasmine/Env.js:157

**Comment by bamthomas** [comment]
It is comming from `store.commit('search/reset')` in afterEach via [Facet.watchedForUpdate](https://github.com/ICIJ/datashare-client/blob/master/src/components/Facet.vue#L163).
the `watchedForUpdate` is making a search HTTP request that is done after the [afterAll](https://github.com/ICIJ/datashare-client/blob/master/tests/unit/specs/utils/esConnectionHelper.js#L20) that deletes the index

The `afterEach` is actually called before the `afterAll` but there is a delay before Viewjs sees changes.

This issue is occurring only for tests that are making global search, because the state is refreshed. i.e. FacetText and FacetSearch tests.
