### ISSUE TITLE
Remove 404 index not found 

### ISSUE THREAD

**Issue by bamthomas** [ICIJ/datashare-client#15]
when running tests, lots of errors like : 

      [index_not_found_exception] no such index, with { resource.type="index_or_alias" & resource.id="datashare-testjs" & index_uuid="_na_" & index="datashare-testjs" } :: {"path":"/datashare-testjs/doc/_search","query":{},"body":"{\"size\":0,\"query\":{\"bool\":{\"must\":[{\"match_all\":{}},{\"bool\":{\"should\":[{\"query_string\":{\"query\":\"*\",\"default_field\":\"*\"}},{\"has_parent\":{\"parent_type\":\"Document\",\"inner_hits\":{\"size\":30},\"query\":{\"match\":{\"content\":\"*\"}}}}]}}]}},\"aggs\":{\"contentType\":{\"terms\":{\"field\":\"contentType\",\"size\":8,\"include\":\".*().*\"}}}}","statusCode":404,"response":"{\"error\":{\"root_cause\":[{\"type\":\"index_not_found_exception\",\"reason\":\"no such index\",\"resource.type\":\"index_or_alias\",\"resource.id\":\"datashare-testjs\",\"index_uuid\":\"_na_\",\"index\":\"datashare-testjs\"}],\"type\":\"index_not_found_exception\",\"reason\":\"no such index\",\"resource.type\":\"index_or_alias\",\"resource.id\":\"datashare-testjs\",\"index_uuid\":\"_na_\",\"index\":\"datashare-testjs\"},\"status\":404}"}
          at respond (/home/dev/src/datashare-client/node_modules/elasticsearch-browser/elasticsearch.js:25294:15)
          at checkRespForFailure (/home/dev/src/datashare-client/node_modules/elasticsearch-browser/elasticsearch.js:25255:7)
          at XMLHttpRequest.xhr.onreadystatechange (/home/dev/src/datashare-client/node_modules/elasticsearch-browser/elasticsearch.js:31549:7)
          at XMLHttpRequest.el.addEventListener.event (/home/dev/src/datashare-client/node_modules/jsdom/lib/jsdom/living/helpers/create-event-accessor.js:33:32)
          at invokeEventListeners (/home/dev/src/datashare-client/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:193:27)
          at XMLHttpRequestEventTargetImpl._dispatch (/home/dev/src/datashare-client/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:119:9)
          at XMLHttpRequestEventTargetImpl.dispatchEvent (/home/dev/src/datashare-client/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:82:17)
          at XMLHttpRequest.dispatchEvent (/home/dev/src/datashare-client/node_modules/jsdom/lib/jsdom/living/generated/EventTarget.js:157:21)
          at readyStateChange (/home/dev/src/datashare-client/node_modules/jsdom/lib/jsdom/living/xmlhttprequest.js:811:9)
          at Request.properties.client.on (/home/dev/src/datashare-client/node_modules/jsdom/lib/jsdom/living/xmlhttprequest.js:939:7)
          at emitOne (events.js:121:20)
          at Request.emit (events.js:211:7)
          at Gunzip.<anonymous> (/home/dev/src/datashare-client/node_modules/request/request.js:1079:12)
          at Object.onceWrapper (events.js:313:30)
          at emitNone (events.js:111:20)
          at Gunzip.emit (events.js:208:7)
          at endReadableNT (_stream_readable.js:1055:12)
          at _combinedTickCallback (internal/process/next_tick.js:138:11)
          at process._tickCallback (internal/process/next_tick.js:180:9)

This may be related to #14

**Comment by annelhote** [comment]
Only one last 404. Admit it's closed.
